version: '3'
services: 
  app:
    build: 
      context: .
    environment:
      ASPNETCORE_HTTPS_PORT: 443
    ports: 
      - '5000:80'
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4tl4nt45
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
